
export const AccordionData = [
    {
      id: 1,
      title: "What was the first human-made object in space?",
      content:
        "The first human-made object to reach space was the V-2 rocket, launched by Germany in 1944. It reached an altitude of 189 km, crossing the Kármán line, which is commonly used to define the edge of space.",
    },
    {
      id: 2,
      title: "Who was the first person in space?",
      content:
        "Yuri Gagarin, a Soviet cosmonaut, became the first human in space on April 12, 1961, aboard the spacecraft Vostok 1. His flight lasted just 108 minutes.",
    },
    {
      id: 3,
      title: "What is the International Space Station (ISS)?",
      content:
        "The ISS is a habitable satellite that orbits Earth and serves as a research lab for scientists. It is a joint project involving NASA, Roscosmos, ESA, JAXA, and CSA.",
    },
    {
      id: 4,
      title: "What is a light-year?",
      content:
        "A light-year is the distance light travels in one year—about 9.46 trillion kilometers. It’s used to measure astronomical distances between stars and galaxies.",
    },
    {
      id: 5,
      title: "Has any human been to Mars?",
      content:
        "No human has been to Mars yet. All Mars exploration has been carried out by robotic spacecraft, such as rovers like Curiosity and Perseverance.",
    },
    {
      id: 6,
      title: "How do rockets escape Earth's gravity?",
      content:
        "Rockets achieve escape velocity—about 11.2 km/s—using thrust generated by burning fuel. This overcomes Earth's gravitational pull and allows them to reach space.",
    },
    {
      id: 7,
      title: "What is a black hole?",
      content:
        "A black hole is a region in space where gravity is so intense that nothing, not even light, can escape from it. They form when massive stars collapse at the end of their life cycles.",
    },
  ];
  